# docker-compose.yml

version: '3.8'

services:
  streamer:
    # Build the Docker image using the Dockerfile in the current directory (.)
    build: .
    
    # Name the resulting container for easy identification
    container_name: media-service
    
    # REMOVED: No longer exposing the port to the host.
    # Nginx will be the only public entry point. The 'streamer' service
    # only needs to be accessible by other services within the Docker network.
    # Map port 8080 on the host to port 8080 in the container
    # ports:
    #   - "${DOCKER_HOST_PORT}:8080"

    # Mount a host directory into the container.
    # ${VIDEO_HOST_PATH} will be read from the .env file.
    volumes:
      - "${MEDIA_HOST_PATH}:/data/media"

    # Load environment variables from our production file for the
    # Node.js app.
    env_file:
      - .env

    # Define the environment variables for the Node.js application inside the container
    environment:
      # This path is *inside* the container and matches the volume mount target below
      - MEDIA_DIR=/data/media

    # Automatically restart the container if it crashes
    restart: unless-stopped

  # The Nginx reverse proxy service
  nginx:
    # Use the official Nginx image from Docker Hub
    image: nginx:latest
    container_name: nginx-proxy
    # Map port 80 on the host to port 80 in the Nginx container.
    # This is now our public entry point.
    ports:
      - "80:80"
      # You would add "443:443" here for HTTPS
    volumes:
      # Mount our custom nginx.conf into the container, overwriting the default.
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # This ensures the 'streamer' service is started before Nginx starts.
    # Nginx needs the 'streamer' service to be running to proxy requests to it.
    depends_on:
      - streamer