# docker-compose.yml

version: '3.8'

services:
  streamer:
    # Build the Docker image using the Dockerfile in the current directory (.)
    build: .
    
    # Name the resulting container for easy identification
    container_name: video-service
    
    # Map port 8080 on the host to port 8080 in the container
    ports:
      - "8080:8080"
      
    # Define the environment variables for the Node.js application inside the container
    environment:
      # This path is *inside* the container and matches the volume mount target below
      - VIDEO_DIR=/data/videos
      
    # Mount a host directory into the container.
    # ${VIDEO_HOST_PATH} will be read from the .env file.
    volumes:
      - "${VIDEO_HOST_PATH}:/data/videos"
      
    # Automatically restart the container if it crashes
    restart: unless-stopped